### ISSUE TITLE
Replace deprecated set-output function with GITHUB_OUTPUT

### ISSUE THREAD

**Issue by mhnaeem** [tspascoal/get-user-teams-membership#13]
The `::set-output::` function has been deprecated in favour of using the `GITHUB_OUTPUT` environment file. This change was also reflected in the `@actions/core` repo which needs to have it's version updated to remove warnings.

Ref: The set-output function is insecure according to this notification: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by tspascoal** [comment]
closed in #13
